# Nightly
indent_style = "Block"
binop_separator = "Front"
combine_control_expr = true
comment_width = 0
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
disable_all_formatting = false
error_on_line_overflow = false
error_on_unformatted = false
fn_args_layout = "Tall"
brace_style = "AlwaysNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_single_line = false
where_single_line = false
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
imports_indent = "Block"
imports_layout = "Vertical"
merge_imports = true
match_block_trailing_comma = false
force_multiline_blocks = true
normalize_comments = true
reorder_impl_items = true
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
format_code_in_doc_comments = true
wrap_comments = false
match_arm_blocks = true
overflow_delimited_expr = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
# required_version = CARGO_PKG_VERSION
hide_parse_errors = false
color = "Always"
unstable_features = true
# license_template_path
normalize_doc_attributes = true

# Stable
use_small_heuristics = "Default"
force_explicit_abi = true
hard_tabs = true
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = false
use_try_shorthand = true
edition = "2018"
